-- SQL script to set up a new Snowflake account for tests and GitHub workflows
-- Replace replace <password> placeholder statement with an actual password of your choice

SET PASSWORD = '<password>';  -- replace with actual password of your choice

---

USE ROLE ACCOUNTADMIN;

CREATE ROLE SNOWKILL_ADMIN_TEST;

CREATE WAREHOUSE SNOWKILL_WH
WAREHOUSE_SIZE = 'XSMALL'
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 4
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE SNOWKILL_NO_SCALE_WH
WAREHOUSE_SIZE = 'XSMALL'
MAX_CONCURRENCY_LEVEL = 1
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE USER SNOWKILL_TEST
PASSWORD = $PASSWORD
DEFAULT_ROLE = SNOWKILL_ADMIN_TEST
DEFAULT_WAREHOUSE = SNOWKILL_WH;

GRANT ROLE SNOWKILL_ADMIN_TEST TO USER SNOWKILL_TEST;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SNOWKILL_ADMIN_TEST;
GRANT MANAGE WAREHOUSES ON ACCOUNT TO ROLE SNOWKILL_ADMIN_TEST;

---

CREATE DATABASE SNOWKILL_TEST;

CREATE TABLE SNOWKILL_TEST.PUBLIC.SNOWKILL_LOG
(
    query_id VARCHAR(16777216),
    check_result_level NUMBER(38,0),
    check_result_name VARCHAR(16777216),
    check_result_description VARCHAR(16777216),
    check_result_time TIMESTAMP_NTZ(6)
);

CREATE TABLE SNOWKILL_TEST.PUBLIC.TABLE_1
(
    id NUMBER(38,0),
    name VARCHAR(255)
);
